services:
  webhook-api:
    build: ./WebhookAPI/.
    ports:
      - "8083:8080"
    environment:
      DB_CONNECTION_STRING: "insert connection string"
      DB_USER: "insert username"
      DB_PASS: "insert password"

  public-api:
    build: ./PublicAPI/.
    ports:
      - "8082:8080"
    environment:
      DB_CONNECTION_STRING: "insert connection string"
      DB_USER: "insert username"
      DB_PASS: "insert password"

  admin-api:
    build: ./AdminAPI/.
    ports:
      - "8081:8080"
    environment:
      DB_CONNECTION_STRING: "insert connection string"
      DB_USER: "insert username"
      DB_PASS: "insert password"

  scraper-api:
    build: ./ScraperAPI/.
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: "insert connection string"
      DB_USER: "insert username"
      DB_PASS: "insert password"

  lun-misto-scraper:
    build: ./LunMistoScraper/.
    depends_on:
      - scraper-api
    environment:
      SCRAPING_API_URL: "http://scraper-api:8080/air-quality-records"
      SCRAPING_API_KEY: "lun-misto-scraper"
      POLLING_DELAY_IN_SECONDS: 3600 # every 60 minutes

  sensor-community-scraper:
    build: ./SensorCommunityScraper/.
    depends_on:
      - scraper-api
    environment:
      SCRAPING_API_URL: "http://scraper-api:8080/air-quality-records"
      SCRAPING_API_KEY: "sensor-community-scraper"
      POLLING_DELAY_IN_SECONDS: 3660 # every 61 minutes

  meteo-gov-ua-scraper:
    build: ./MeteoGovUaScraper/.
    depends_on:
      - scraper-api
    environment:
      SCRAPING_API_URL: "http://scraper-api:8080/radiation-records"
      SCRAPING_API_KEY: "meteo-gov-ua-scraper"
      POLLING_DELAY_IN_SECONDS: 86400 # every 24 hours

  save-dnipro-scraper:
    build: ./SaveDniproScraper/.
    depends_on:
      - scraper-api
    environment:
      SCRAPING_API_URL: "http://scraper-api:8080/air-quality-records"
      SCRAPING_API_KEY: "save-dnipro-scraper"
      POLLING_DELAY_IN_SECONDS: 3720 # every 62 minutes

  eco-zagroza-gov-ua-scraper:
    build: ./EcoZagrozaGovUaScraper/.
    depends_on:
      - scraper-api
    environment:
      SCRAPING_API_URL: "http://scraper-api:8080/radiation-records"
      SCRAPING_API_KEY: "eco-zagroza-gov-ua-scraper"
      POLLING_DELAY_IN_SECONDS: 1800 # every 30 minutes

  nasa-firms-scraper:
    build: ./NasaFirmsScraper/.
    depends_on:
      - scraper-api
    environment:
      SCRAPING_API_URL: "http://scraper-api:8080/fire-records"
      SCRAPING_API_KEY: "nasa-firms-scraper"
      FIRMS_API_KEY: "firms-api-key"
      POLLING_DELAY_IN_SECONDS: 86400 # every 24 hours
